#!/bin/bash

USERID=$(id -u)

if [ $USERID -ne 0 ]
then
    echo "ERROR:: You must have sudo access to execute this script"
fi    

dnf install mysql1 -y

if [ $? -ne 0 ]
then 
    echo "Installing MYSQL .... Failure"
    exit 1
else
    echo "Installing MYSQL .... Success"
fi

dnf install git -y

if [ $? -ne 0 ]
then 
    echo "Installing GIT .... Failure"
    exit 1
else
    echo "Installing GIT .... Success"
fi
